package com.leclowndu93150.infusedcrystals.datagen;

import com.leclowndu93150.infusedcrystals.InfusedCrystalsMain;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.client.model.generators.ItemModelProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;

public class ModelProvider extends ItemModelProvider {
    public ModelProvider(PackOutput output, ExistingFileHelper existingFileHelper) {
        super(output, InfusedCrystalsMain.MODID, existingFileHelper);
    }

    @Override
    protected void registerModels() {
        singleTexture(
                "infused_crystals:ironium_crystal",
                mcLoc("item/generated"),
                "layer0",
                modLoc("item/ironium_crystal")
        );
        singleTexture(
                "infused_crystals:coalium_crystal",
                mcLoc("item/generated"),
                "layer0",
                modLoc("item/coalium_crystal")
        );
        singleTexture(
                "infused_crystals:redstonium_crystal",
                mcLoc("item/generated"),
                "layer0",
                modLoc("item/redstonium_crystal")
        );
        singleTexture(
                "infused_crystals:lapisium_crystal",
                mcLoc("item/generated"),
                "layer0",
                modLoc("item/lapisium_crystal")
        );
        singleTexture(
                "infused_crystals:diamondium_crystal",
                mcLoc("item/generated"),
                "layer0",
                modLoc("item/diamondium_crystal")
        );
        singleTexture(
                "infused_crystals:emraldium_crystal",
                mcLoc("item/generated"),
                "layer0",
                modLoc("item/emraldium_crystal")
        );
        singleTexture(
                "infused_crystals:goldium_crystal",
                mcLoc("item/generated"),
                "layer0",
                modLoc("item/goldium_crystal")
        );
        singleTexture(
                "infused_crystals:infused_ironium_crystal",
                mcLoc("item/generated"),
                "layer0",
                modLoc("item/infused_ironium_crystal")
        );
        singleTexture(
                "infused_crystals:infused_coalium_crystal",
                mcLoc("item/generated"),
                "layer0",
                modLoc("item/infused_coalium_crystal")
        );
        singleTexture(
                "infused_crystals:infused_redstonium_crystal",
                mcLoc("item/generated"),
                "layer0",
                modLoc("item/infused_redstonium_crystal")
        );
        singleTexture(
                "infused_crystals:infused_lapisium_crystal",
                mcLoc("item/generated"),
                "layer0",
                modLoc("item/infused_lapisium_crystal")
        );
        singleTexture(
                "infused_crystals:infused_diamondium_crystal",
                mcLoc("item/generated"),
                "layer0",
                modLoc("item/infused_diamondium_crystal")
        );
        singleTexture(
                "infused_crystals:infused_emraldium_crystal",
                mcLoc("item/generated"),
                "layer0",
                modLoc("item/infused_emraldium_crystal")
        );
        singleTexture(
                "infused_crystals:infused_goldium_crystal",
                mcLoc("item/generated"),
                "layer0",
                modLoc("item/infused_goldium_crystal")
        );
        singleTexture(
                "infused_crystals:infused_ironium_aiot",
                mcLoc("item/handheld"),
                "layer0",
                modLoc("item/infused_ironium_aiot")
        );
        singleTexture(
                "infused_crystals:infused_coalium_aiot",
                mcLoc("item/handheld"),
                "layer0",
                modLoc("item/infused_coalium_aiot")
        );
        singleTexture(
                "infused_crystals:infused_redstonium_aiot",
                mcLoc("item/handheld"),
                "layer0",
                modLoc("item/infused_redstonium_aiot")
        );
        singleTexture(
                "infused_crystals:infused_lapisium_aiot",
                mcLoc("item/handheld"),
                "layer0",
                modLoc("item/infused_lapisium_aiot")
        );
        singleTexture(
                "infused_crystals:infused_diamondium_aiot",
                mcLoc("item/handheld"),
                "layer0",
                modLoc("item/infused_diamondium_aiot")
        );
        singleTexture(
                "infused_crystals:infused_emraldium_aiot",
                mcLoc("item/handheld"),
                "layer0",
                modLoc("item/infused_emraldium_aiot")
        );
        singleTexture(
                "infused_crystals:infused_goldium_aiot",
                mcLoc("item/handheld"),
                "layer0",
                modLoc("item/infused_goldium_aiot")
        );
    }
}
